sudo: required
services:
  - docker

env:
  - IMGTAG=debian8
  - IMGTAG=debian9
  - IMGTAG=fedora25
  - IMGTAG=ubuntu16.04
  - IMGTAG=ubuntu17.04

before_install:
- docker pull exaile/exaile-testimg:${IMGTAG}

script:
- docker run --rm -it -e HOME=/home -v $(pwd):/app -w /app exaile/exaile-testimg:${IMGTAG} make test

notifications:
  irc:
    channels:
    - "chat.freenode.net#exaile"
    use_notice: true
    skip_join: true
    on_success: change